### ISSUE TITLE
linux运行出现以下报错

### ISSUE THREAD

**Issue by YoumyTheGoust** [ranyong1997/sk#3]
Traceback (most recent call last):
  File "StartWork.py", line 13, in <module>
    for key, value in mooc_init.get_user_all().items():
  File "/root/sk/common/initMooc.py", line 218, in get_user_all
    with open("data/data.csv", "r", encoding='gbk') as csvFile:
FileNotFoundError: [Errno 2] No such file or directory: 'data/data.csv'

**Comment by RanY-Luck** [comment]
这是因为我当时是写入csv文件批量刷课的，如果只刷一门的话 就直接在里面填写账号密码就好了
